version: '3.8'

services:
  gotenberg:
    build:
      context: .
      dockerfile: gotenberg.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - LOG_LEVEL=DEBUG
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
