name = "lytsite-backend"
main = "src/worker.ts"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

# Enable logging for debugging
[observability.logs]
enabled = true

[vars]
ENVIRONMENT = "production"
# LibreOffice conversion service URLs (update with your deployed services)
# 1. AWS ALB for LibreOffice service (primary) - much more reliable than API Gateway
# 2. Deploy Gotenberg to Railway: https://railway.app/template/gotenberg
# 3. Sign up for CloudMersive free tier: https://cloudmersive.com/ (3.5MB limit)
AWS_CONVERTER_URL = "http://libreoffice-converter-alb-1434889223.ap-south-1.elb.amazonaws.com"
# AWS_ACCESS_KEY_ID = "set via wrangler secret put AWS_ACCESS_KEY_ID"
# AWS_SECRET_ACCESS_KEY = "set via wrangler secret put AWS_SECRET_ACCESS_KEY"
AWS_REGION = "ap-south-1"
GOTENBERG_SERVICE_URL = "https://your-gotenberg-service.railway.app"
CLOUDMERSIVE_API_KEY = "your-cloudmersive-api-key"
ONLYOFFICE_SERVER_URL = "https://your-onlyoffice-server.com"

[[kv_namespaces]]
binding = "LYTSITE_KV"
id = "db777c41abe84ba1813134377bc23808"
preview_id = "db777c41abe84ba1813134377bc23808"

[[r2_buckets]]
binding = "LYTSITE_STORAGE"
bucket_name = "lytsite-files"
preview_bucket_name = "lytsite-files-preview"

# D1 Database for advanced features
[[d1_databases]]
binding = "LYTSITE_DB"
database_name = "lytsite-advanced"
database_id = "9a6c141f-f6a2-4e0b-9026-d76af0491672"

# Serve static assets from dist-standalone directory
[assets]
directory = "../dist-standalone"
binding = "ASSETS"

[env.production]
name = "lytsite-backend-prod"

[env.production.vars]
ENVIRONMENT = "production"
AWS_CONVERTER_URL = "http://3.110.196.217:8080"
GOTENBERG_SERVICE_URL = "https://your-gotenberg-service.railway.app"
CLOUDMERSIVE_API_KEY = "your-cloudmersive-api-key"
ONLYOFFICE_SERVER_URL = "https://your-onlyoffice-server.com"

[[env.production.kv_namespaces]]
binding = "LYTSITE_KV"
id = "db777c41abe84ba1813134377bc23808"

[[env.production.r2_buckets]]
binding = "LYTSITE_STORAGE"
bucket_name = "lytsite-files"

# Production D1 Database
[[env.production.d1_databases]]
binding = "LYTSITE_DB"
database_name = "lytsite-advanced-prod"
database_id = "9bc937ea-c481-4ad3-b548-50a3b3cf9a7a"

# Serve static assets from dist-standalone directory
[env.production.assets]
directory = "../dist-standalone"
binding = "ASSETS"
